### ISSUE TITLE
[Crash on Startup] Fabric 1.20.1 - BFR 0.1.5 (latest release) server startup fail

### ISSUE THREAD

**Issue by LokeYourC3PH** [Wilyicaro/BetterFurnacesReforged#101]
**Mod Version-Minecraft Version**
Minecraft: 1.20.1
Mod Loader: Fabric
BFR: 0.1.5

**Bug/Glitch Occurrence Context**
Updating from 0.1.4 to 0.1.5 causes the Fabric server to fail when starting. This does not occur on the client however, only on the server.

*Crash Report

```
[18:37:40] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'betterfurnacesreforged'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.21.jar:?]
	at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.21.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_746
	at wily.betterfurnaces.BetterFurnacesReforged.init(BetterFurnacesReforged.java:38) ~[BetterFurnaces-1.20.1-0.1.5-fabric.jar:?]
	at wily.betterfurnaces.fabric.BetterFurnacesFabric.onInitialize(BetterFurnacesFabric.java:29) ~[BetterFurnaces-1.20.1-0.1.5-fabric.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
	... 7 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_746
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at wily.betterfurnaces.BetterFurnacesReforged.init(BetterFurnacesReforged.java:38) ~[BetterFurnaces-1.20.1-0.1.5-fabric.jar:?]
	at wily.betterfurnaces.fabric.BetterFurnacesFabric.onInitialize(BetterFurnacesFabric.java:29) ~[BetterFurnaces-1.20.1-0.1.5-fabric.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
	... 7 more
```

**What went wrong**
While 0.1.4 works just fine, both on the client and the server, 0.1.5 (released today) does not work on the server, while it does work fine on the client. Expected behaviour, is of course that the server side version loads the same way as the client version does.

**Comment by Wilyicaro** [comment]
Fixed in 1.20.1-0.1.6, if you have more problems, just report :)
