### ISSUE TITLE
[Crash] 1.20.1 Fabric Repeating Crush

### ISSUE THREAD

**Issue by Giinkie** [Wilyicaro/BetterFurnacesReforged#107]
1. Better Furnace 0.1.7-fabric - Minecraft 1.20.1

2. Fabric-loader-0.14.21-1.20.1

3. Crash after 1 minute in game, again and again after every restart my world. In other worlds, than i don't place furnace - everything alright.

4. Crash Report
Description: Ticking block entity

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_5819.method_43048(int)" because "$$2" is null
	at net.minecraft.class_1885.method_8176(class_1885.java:40)
	at net.minecraft.class_1799.method_7970(class_1799.java:343)
	at wily.betterfurnaces.blockentity.InventoryBlockEntity.breakDurabilityItem(InventoryBlockEntity.java:91)
	at wily.betterfurnaces.blockentity.SmeltingBlockEntity.tick(SmeltingBlockEntity.java:535)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:662)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:716)
	at net.minecraft.class_1937.method_18471(class_1937.java:470)
	at net.minecraft.class_3218.method_18765(class_3218.java:390)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Unknown Source)

5. I have so many mods, but it's second big crash i had in 40+ hours play. First was incompability Sodium and Omni-Hopper, but i tweak one line, and everything was okay. Hope, you faster fix that, because my main world is dead right now :(
Good luck, and thanks for good mod!

**Comment by Giinkie** [comment]
[crash-2023-07-08_02.25.27-server.txt](https://github.com/Wilyicaro/BetterFurnacesReforged/files/11986872/crash-2023-07-08_02.25.27-server.txt)
That is full crash report, if you want it.

**Comment by LostWorld48** [comment]
I am having the same error

**Comment by Wilyicaro** [comment]
Thanks for reporting the bug, and as I said before disabling comments on the BFR CurseForge page, it's a simple problem, it will be fixed as soon as I have the chance, probably tomorrow

**Comment by Wilyicaro** [comment]
And also to elaborate further, this issue is most likely related to using breakable upgrades like the base versions of Fuel Efficiency and Ore Processing upgrades
