### ISSUE TITLE
Disconnected on join while having a Advanced Ore Processing Upgrade in inventory

### ISSUE THREAD

**Issue by Beaast-exe** [Wilyicaro/BetterFurnacesReforged#25]
Hello
I'm playing a custom modpack with the Better Furnaces mod on it.
I crafted the Advanced Ore Processing Upgrade.
Now whenever i try to join with it in my inventory, i get disconnected.

Stacktrace:
`net.minecraft.util.ReportedException: Ticking player
        at net.minecraft.entity.player.EntityPlayerMP.onUpdateEntity(EntityPlayerMP.java:459) ~[oq.class:?]
        at net.minecraft.network.NetHandlerPlayServer.redirect$zil000$impl$onPlayerTick(NetHandlerPlayServer.java:2504) ~[pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.update(NetHandlerPlayServer.java:173) ~[pa.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.update(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
        at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:285) ~[gw.class:?]
        at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:180) [oz.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:790) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
        at wily.betterfurnaces.items.ItemUpgrade.onUpdate(ItemUpgrade.java:65) ~[ItemUpgrade.class:?]
        at net.minecraft.item.ItemStack.updateAnimation(ItemStack.java:526) ~[aip.class:?]
        at net.minecraft.entity.player.InventoryPlayer.decrementAnimations(InventoryPlayer.java:363) ~[aec.class:?]
        at net.minecraft.entity.player.EntityPlayer.onLivingUpdate(EntityPlayer.java:511) ~[aed.class:?]
        at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2179) ~[vp.class:?]
        at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:234) ~[aed.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.onUpdateEntity(EntityPlayerMP.java:382) ~[oq.class:?]
        ... 10 more
[14:10:41] [Server thread/INFO] [minecraft/NetHandlerPlayServer]: Beaast_exe lost connection: Disconnected`

**Comment by Wilyicaro** [comment]
Fixed in version 1.12.2-1.5 :)
