### ISSUE TITLE
Server Crash, Mod doesn't work.

### ISSUE THREAD

**Issue by Hydraxuz** [Wilyicaro/BetterFurnacesReforged#27]
Mod Version: 1.18.1 1.2.3 

Minecraft 1.18.1

Forge Version 1.18.1 39.0.58

---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 1/23/22, 10:08 AM
Description: Exception ticking world

java.lang.NoSuchMethodError: 'net.minecraft.nbt.CompoundTag net.minecraft.world.level.block.entity.BlockEntity.save(net.minecraft.nbt.CompoundTag)'
	at wily.betterfurnaces.blockentity.BlockEntityInventory.save(BlockEntityInventory.java:175) ~[BetterFurnacesReforged-1.18.1-1.2.3.jar%2339!/:1.18.1-1.2.3] {re:classloading}
	at wily.betterfurnaces.blockentity.BlockEntitySmeltingBase.save(BlockEntitySmeltingBase.java:805) ~[BetterFurnacesReforged-1.18.1-1.2.3.jar%2339!/:1.18.1-1.2.3] {re:classloading}
	at wily.betterfurnaces.blockentity.BlockEntityInventory.m_5995_(BlockEntityInventory.java:75) ~[BetterFurnacesReforged-1.18.1-1.2.3.jar%2339!/:1.18.1-1.2.3] {re:classloading}
	at net.minecraft.network.protocol.game.ClientboundBlockEntityDataPacket.m_195642_(ClientboundBlockEntityDataPacket.java:21) ~[server-1.18.1-20211210.034407-srg.jar%2360!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ClientboundBlockEntityDataPacket.m_195640_(ClientboundBlockEntityDataPacket.java:25) ~[server-1.18.1-20211210.034407-srg.jar%2360!/:?] {re:classloading}
	at wily.betterfurnaces.blockentity.BlockEntityInventory.getUpdatePacket(BlockEntityInventory.java:60) ~[BetterFurnacesReforged-1.18.1-1.2.3.jar%2339!/:1.18.1-1.2.3] {re:classloading}
	at wily.betterfurnaces.blockentity.BlockEntityInventory.m_183216_(BlockEntityInventory.java:30) ~[BetterFurnacesReforged-1.18.1-1.2.3.jar%2339!/:1.18.1-1.2.3] {re:classloading}
	at net.minecraft.server.level.ChunkHolder.m_140029_(ChunkHolder.java:228) ~[server-1.18.1-20211210.034407-srg.jar%2360!/:?] {re:classloading}
	at net.minecraft.server.level.ChunkHolder.m_140032_(ChunkHolder.java:220) ~[server-1.18.1-20211210.034407-srg.jar%2360!/:?] {re:classloading}
	at net.minecraft.server.level.ChunkHolder.m_140054_(ChunkHolder.java:200) ~[server-1.18.1-20211210.034407-srg.jar%2360!/:?] {re:classloading}
	at net.minecraft.server.level.ServerChunkCache.m_184021_(ServerChunkCache.java:371) ~[server-1.18.1-20211210.034407-srg.jar%2360!/:?] {re:classloading,pl:accesstransformer:B}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {}
	at net.minecraft.server.level.ServerChunkCache.m_8490_(ServerChunkCache.java:370) ~[server-1.18.1-20211210.034407-srg.jar%2360!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerChunkCache.m_142483_(ServerChunkCache.java:311) ~[server-1.18.1-20211210.034407-srg.jar%2360!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:278) ~[server-1.18.1-20211210.034407-srg.jar%2360!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:868) ~[server-1.18.1-20211210.034407-srg.jar%2360!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:328) ~[server-1.18.1-20211210.034407-srg.jar%2360!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[server-1.18.1-20211210.034407-srg.jar%2360!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[server-1.18.1-20211210.034407-srg.jar%2360!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%2360!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at wily.betterfurnaces.blockentity.BlockEntityInventory.save(BlockEntityInventory.java:175) ~[BetterFurnacesReforged-1.18.1-1.2.3.jar%2339!/:1.18.1-1.2.3] {re:classloading}
	at wily.betterfurnaces.blockentity.BlockEntitySmeltingBase.save(BlockEntitySmeltingBase.java:805) ~[BetterFurnacesReforged-1.18.1-1.2.3.jar%2339!/:1.18.1-1.2.3] {re:classloading}
	at wily.betterfurnaces.blockentity.BlockEntityInventory.m_5995_(BlockEntityInventory.java:75) ~[BetterFurnacesReforged-1.18.1-1.2.3.jar%2339!/:1.18.1-1.2.3] {re:classloading}
	at net.minecraft.network.protocol.game.ClientboundBlockEntityDataPacket.m_195642_(ClientboundBlockEntityDataPacket.java:21) ~[server-1.18.1-20211210.034407-srg.jar%2360!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ClientboundBlockEntityDataPacket.m_195640_(ClientboundBlockEntityDataPacket.java:25) ~[server-1.18.1-20211210.034407-srg.jar%2360!/:?] {re:classloading}
	at wily.betterfurnaces.blockentity.BlockEntityInventory.getUpdatePacket(BlockEntityInventory.java:60) ~[BetterFurnacesReforged-1.18.1-1.2.3.jar%2339!/:1.18.1-1.2.3] {re:classloading}
	at wily.betterfurnaces.blockentity.BlockEntityInventory.m_183216_(BlockEntityInventory.java:30) ~[BetterFurnacesReforged-1.18.1-1.2.3.jar%2339!/:1.18.1-1.2.3] {re:classloading}
	at net.minecraft.server.level.ChunkHolder.m_140029_(ChunkHolder.java:228) ~[server-1.18.1-20211210.034407-srg.jar%2360!/:?] {re:classloading}
	at net.minecraft.server.level.ChunkHolder.m_140032_(ChunkHolder.java:220) ~[server-1.18.1-20211210.034407-srg.jar%2360!/:?] {re:classloading}
	at net.minecraft.server.level.ChunkHolder.m_140054_(ChunkHolder.java:200) ~[server-1.18.1-20211210.034407-srg.jar%2360!/:?] {re:classloading}
	at net.minecraft.server.level.ServerChunkCache.m_184021_(ServerChunkCache.java:371) ~[server-1.18.1-20211210.034407-srg.jar%2360!/:?] {re:classloading,pl:accesstransformer:B}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {}
	at net.minecraft.server.level.ServerChunkCache.m_8490_(ServerChunkCache.java:370) ~[server-1.18.1-20211210.034407-srg.jar%2360!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerChunkCache.m_142483_(ServerChunkCache.java:311) ~[server-1.18.1-20211210.034407-srg.jar%2360!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:278) ~[server-1.18.1-20211210.034407-srg.jar%2360!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
-- Affected level --
Details:
	All players: 1 total; [ServerPlayer['Hydraxuz'/63, l='ServerLevel[Hydraxia]', x=-84.16, y=117.00, z=64.30]]
	Chunk stats: 3481
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,135,0), Section: (at 0,7,0 in 0,8,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 35955896 game time, 2084830 day time
	Level name: Hydraxia
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 47703 (now: false), thunder time: 7318 (now: true)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:868) ~[server-1.18.1-20211210.034407-srg.jar%2360!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:328) ~[server-1.18.1-20211210.034407-srg.jar%2360!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[server-1.18.1-20211210.034407-srg.jar%2360!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[server-1.18.1-20211210.034407-srg.jar%2360!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%2360!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Linux (amd64) version 3.10.0-1160.6.1.el7.x86_64
	Java Version: 17.0.1, Red Hat, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Red Hat, Inc.
	Memory: 607136336 bytes (579 MiB) / 3170893824 bytes (3024 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 40
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz
	Identifier: Intel64 Family 6 Model 79 Stepping 1
	Microarchitecture: Broadwell (Server)
	Frequency (GHz): 2.20
	Number of physical packages: 2
	Number of physical CPUs: 20
	Number of logical CPUs: 40
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 132941.69
	Virtual memory used (MB): 250209.70
	Swap memory total (MB): 4096.00
	Swap memory used (MB): 4096.00
	JVM Flags: 20 total; -Xmx6144M -XX:+UseContainerSupport -XX:MaxMetaspaceSize=512M -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=8 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:MaxTenuringThreshold=1
	Server Running: true
	Player Count: 1 / 100; [ServerPlayer['Hydraxuz'/63, l='ServerLevel[Hydraxia]', x=-84.16, y=117.00, z=64.30]]
	Data Packs: vanilla, mod:framedblocks, mod:mousetweaks, mod:expandedstorage, mod:trashslot, mod:biomesoplenty, mod:balm (incompatible), mod:jei, mod:ninjaphenix_container_lib, mod:forge, mod:appleskin (incompatible), mod:majrusz_library (incompatible), mod:wonderful_enchantments (incompatible), mod:clumps (incompatible), mod:oresabovediamonds (incompatible), mod:journeymap, mod:naturescompass (incompatible), mod:timber (incompatible), mod:enchdesc, mod:terrablender, mod:hunterillager, mod:enchantwithmob, mod:revampedwolf, mod:betterfurnacesreforged (incompatible)
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)
	ModLauncher: 9.1.0+9.1.0+main.6690ee51
	ModLauncher launch target: forgeserver
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		server-1.18.1-20211210.034407-srg.jar             |Minecraft                     |minecraft                     |1.18.1              |DONE      |Manifest: NOSIGNATURE
		FramedBlocks-4.1.0.jar                            |FramedBlocks                  |framedblocks                  |4.1.0               |DONE      |Manifest: NOSIGNATURE
		EnchantmentDescriptions-Forge-1.18.1-9.0.12.jar   |EnchantmentDescriptions       |enchdesc                      |9.0.12              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		TerraBlender-forge-1.18.1-1.1.0.73.jar            |TerraBlender                  |terrablender                  |1.18.1-1.1.0.73     |DONE      |Manifest: NOSIGNATURE
		MouseTweaks-forge-mc1.18-2.21.jar                 |Mouse Tweaks                  |mousetweaks                   |2.21                |DONE      |Manifest: NOSIGNATURE
		expandedstorage-7.3.6+1.18.jar                    |Expanded Storage              |expandedstorage               |7.3.6               |DONE      |Manifest: NOSIGNATURE
		trashslot-forge-1.18-11.0.1.jar                   |TrashSlot                     |trashslot                     |11.0.1              |DONE      |Manifest: NOSIGNATURE
		BiomesOPlenty-1.18.1-15.0.0.104-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.18.1-15.0.0.104   |DONE      |Manifest: NOSIGNATURE
		HunterIllager-1.18.1-3.1.0.jar                    |Hunter Illager                |hunterillager                 |1.18.1-3.1.0        |DONE      |Manifest: NOSIGNATURE
		BetterFurnacesReforged-1.18.1-1.2.3.jar           |BetterFurnaces Reforged       |betterfurnacesreforged        |1.18.1-1.2.3        |DONE      |Manifest: NOSIGNATURE
		balm-2.4.1+0.jar                                  |Balm                          |balm                          |2.4.1+0             |DONE      |Manifest: NOSIGNATURE
		jei-1.18.1-9.2.3.78.jar                           |Just Enough Items             |jei                           |9.2.3.78            |DONE      |Manifest: NOSIGNATURE
		enchantwithmob-1.18.1-3.1.0.jar                   |Enchant With Mob              |enchantwithmob                |1.18.1-3.1.0        |DONE      |Manifest: NOSIGNATURE
		ninjaphenix-container-library-1.2.10+1.18.jar     |NinjaPhenix's Container Librar|ninjaphenix_container_lib     |1.2.10              |DONE      |Manifest: NOSIGNATURE
		forge-1.18.1-39.0.58-universal.jar                |Forge                         |forge                         |39.0.58             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		appleskin-forge-mc1.18-2.2.0.jar                  |AppleSkin                     |appleskin                     |2.2.0               |DONE      |Manifest: NOSIGNATURE
		majrusz-library-1.18.1-2.7.1.jar                  |Majrusz Library               |majrusz_library               |2.7.1               |DONE      |Manifest: NOSIGNATURE
		wonderful-enchantments-1.18.1-1.6.1.jar           |Wonderful Enchantments        |wonderful_enchantments        |1.6.1               |DONE      |Manifest: NOSIGNATURE
		revampedwolf-1.18.1-1.1.0.jar                     |RevampedWolf                  |revampedwolf                  |1.18.1-1.1.0        |DONE      |Manifest: NOSIGNATURE
		timber-1.18.1-3.0.0.jar                           |Timber Mod                    |timber                        |3.0.0               |DONE      |Manifest: NOSIGNATURE
		Clumps-forge-1.18.1-8.0.0+5.jar                   |Clumps                        |clumps                        |8.0.0+5             |DONE      |Manifest: NOSIGNATURE
		oresabovediamonds-1.18.1-v8.0.2.jar               |Ores Above Diamonds           |oresabovediamonds             |8.0.2               |DONE      |Manifest: NOSIGNATURE
		journeymap-1.18.1-5.8.0beta10.jar                 |Journeymap                    |journeymap                    |5.8.0beta10         |DONE      |Manifest: NOSIGNATURE
		NaturesCompass-1.18.1-1.9.4-forge.jar             |Nature's Compass              |naturescompass                |1.18.1-1.9.4-forge  |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 2bfe89b3-d4ca-4b44-9732-8e04314b4cb8
	FML: 39.0
	Forge: net.minecraftforge:39.0.58
	FramedBlocks BlockEntity Warning: Not applicable

What happened wrong:
Firstly, nobody could get into the server because the furnaces were placed. Sadly, removed the mod which fixed the issue. Re-added the mod to see if it would work or not. The server starts up, people can get in and play the game, but as soon as any better furnaces reforged blocks are placed, the whole server crashes. When restarted, it acts as if the block was never placed in the first place. This problem only happens with the better furnaces reforged mod. First happened around 1/22/2022 at 8 pm.

**Comment by Wilyicaro** [comment]
Surely this is some incompatibility that occurred in the new versions of forge, as I tested it on a dedicated server before, and it worked normally

**Comment by Wilyicaro** [comment]
That's really what I thought... the cause of this crash and of the mod not working were small changes that occurred in the new versions of forge. Thank you very much for reporting this issue.

**Comment by Wilyicaro** [comment]
I recommend you use a more outdated version of forge if you want to use my mod for now, not sure when I will be able to post the update that fixes this

**Comment by Wilyicaro** [comment]
It was fixed in version 1.18.1-1.2.4
