### ISSUE TITLE
Game Crashing

### ISSUE THREAD

**Issue by Stormcatcher86** [Wilyicaro/BetterFurnacesReforged#29]
My Single player Minecraft world crashed and won't open after running the extreme furnace. pasting the crash report below. maybe you can tell me what I did wrong?

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 3/12/22, 5:30 PM
Description: Ticking block entity

java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.objects.ObjectArrayList.get(int)" because "this.wrapped" is null
	at it.unimi.dsi.fastutil.objects.Object2IntOpenHashMap$MapIterator.nextEntry(Object2IntOpenHashMap.java:755) ~[fastutil-8.5.6.jar%2348!/:?] {}
	at it.unimi.dsi.fastutil.objects.Object2IntOpenHashMap$EntryIterator.next(Object2IntOpenHashMap.java:853) ~[fastutil-8.5.6.jar%2348!/:?] {}
	at it.unimi.dsi.fastutil.objects.Object2IntOpenHashMap$EntryIterator.next(Object2IntOpenHashMap.java:847) ~[fastutil-8.5.6.jar%2348!/:?] {}
	at wily.betterfurnaces.blockentity.BlockEntitySmeltingBase.grantStoredRecipeExperience(BlockEntitySmeltingBase.java:987) ~[BetterFurnacesReforged-1.18.1-1.2.4.jar%2362!/:1.18.1-1.2.4] {re:classloading,pl:epic_rei_lmao:A}
	at wily.betterfurnaces.blockentity.BlockEntitySmeltingBase.tick(BlockEntitySmeltingBase.java:362) ~[BetterFurnacesReforged-1.18.1-1.2.4.jar%2362!/:1.18.1-1.2.4] {re:classloading,pl:epic_rei_lmao:A}
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:673) ~[client-1.18.1-20211210.034407-srg.jar%2397!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:768) ~[client-1.18.1-20211210.034407-srg.jar%2397!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at net.minecraft.world.level.Level.m_46463_(Level.java:476) ~[client-1.18.1-20211210.034407-srg.jar%2397!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:epic_rei_lmao:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:324) ~[client-1.18.1-20211210.034407-srg.jar%2397!/:?] {re:classloading,pl:accesstransformer:B,pl:epic_rei_lmao:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:868) ~[client-1.18.1-20211210.034407-srg.jar%2397!/:?] {re:classloading,pl:accesstransformer:B,pl:epic_rei_lmao:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[client-1.18.1-20211210.034407-srg.jar%2397!/:?] {re:classloading,pl:accesstransformer:B,pl:epic_rei_lmao:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:120) ~[client-1.18.1-20211210.034407-srg.jar%2397!/:?] {re:classloading,xf:OptiFine:default,pl:epic_rei_lmao:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[client-1.18.1-20211210.034407-srg.jar%2397!/:?] {re:classloading,pl:accesstransformer:B,pl:epic_rei_lmao:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.18.1-20211210.034407-srg.jar%2397!/:?] {re:classloading,pl:accesstransformer:B,pl:epic_rei_lmao:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at it.unimi.dsi.fastutil.objects.Object2IntOpenHashMap$MapIterator.nextEntry(Object2IntOpenHashMap.java:755) ~[fastutil-8.5.6.jar%2348!/:?] {}
	at it.unimi.dsi.fastutil.objects.Object2IntOpenHashMap$EntryIterator.next(Object2IntOpenHashMap.java:853) ~[fastutil-8.5.6.jar%2348!/:?] {}
	at it.unimi.dsi.fastutil.objects.Object2IntOpenHashMap$EntryIterator.next(Object2IntOpenHashMap.java:847) ~[fastutil-8.5.6.jar%2348!/:?] {}
	at wily.betterfurnaces.blockentity.BlockEntitySmeltingBase.grantStoredRecipeExperience(BlockEntitySmeltingBase.java:987) ~[BetterFurnacesReforged-1.18.1-1.2.4.jar%2362!/:1.18.1-1.2.4] {re:classloading,pl:epic_rei_lmao:A}
	at wily.betterfurnaces.blockentity.BlockEntitySmeltingBase.tick(BlockEntitySmeltingBase.java:362) ~[BetterFurnacesReforged-1.18.1-1.2.4.jar%2362!/:1.18.1-1.2.4] {re:classloading,pl:epic_rei_lmao:A}
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:673) ~[client-1.18.1-20211210.034407-srg.jar%2397!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:768) ~[client-1.18.1-20211210.034407-srg.jar%2397!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at net.minecraft.world.level.Level.m_46463_(Level.java:476) ~[client-1.18.1-20211210.034407-srg.jar%2397!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:epic_rei_lmao:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:324) ~[client-1.18.1-20211210.034407-srg.jar%2397!/:?] {re:classloading,pl:accesstransformer:B,pl:epic_rei_lmao:A,re:mixin,pl:accesstransformer:B}
-- Block entity being ticked --
Details:
	Name: betterfurnacesreforged:extreme_forge // wily.betterfurnaces.blockentity.BlockEntityExtremeForge
	Block: Block{betterfurnacesreforged:extreme_forge}[colored=false,facing=up,lit=true,show_orientation=false,waterlogged=false]
	Block location: World: (56,62,45), Section: (at 8,14,13 in 3,3,2; chunk contains blocks 48,-64,32 to 63,319,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Block: Block{betterfurnacesreforged:extreme_forge}[colored=false,facing=up,lit=true,show_orientation=false,waterlogged=false]
	Block location: World: (56,62,45), Section: (at 8,14,13 in 3,3,2; chunk contains blocks 48,-64,32 to 63,319,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
Stacktrace:
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:673) ~[client-1.18.1-20211210.034407-srg.jar%2397!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:768) ~[client-1.18.1-20211210.034407-srg.jar%2397!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at net.minecraft.world.level.Level.m_46463_(Level.java:476) ~[client-1.18.1-20211210.034407-srg.jar%2397!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:epic_rei_lmao:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:324) ~[client-1.18.1-20211210.034407-srg.jar%2397!/:?] {re:classloading,pl:accesstransformer:B,pl:epic_rei_lmao:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:868) ~[client-1.18.1-20211210.034407-srg.jar%2397!/:?] {re:classloading,pl:accesstransformer:B,pl:epic_rei_lmao:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[client-1.18.1-20211210.034407-srg.jar%2397!/:?] {re:classloading,pl:accesstransformer:B,pl:epic_rei_lmao:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:120) ~[client-1.18.1-20211210.034407-srg.jar%2397!/:?] {re:classloading,xf:OptiFine:default,pl:epic_rei_lmao:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[client-1.18.1-20211210.034407-srg.jar%2397!/:?] {re:classloading,pl:accesstransformer:B,pl:epic_rei_lmao:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.18.1-20211210.034407-srg.jar%2397!/:?] {re:classloading,pl:accesstransformer:B,pl:epic_rei_lmao:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: 20970
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,92,0), Section: (at 0,12,0 in 0,5,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 480592 game time, 64362 day time
	Level name: 1.18 Revamped
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
	Level weather: Rain time: 40973 (now: false), thunder time: 76624 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:868) ~[client-1.18.1-20211210.034407-srg.jar%2397!/:?] {re:classloading,pl:accesstransformer:B,pl:epic_rei_lmao:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[client-1.18.1-20211210.034407-srg.jar%2397!/:?] {re:classloading,pl:accesstransformer:B,pl:epic_rei_lmao:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:120) ~[client-1.18.1-20211210.034407-srg.jar%2397!/:?] {re:classloading,xf:OptiFine:default,pl:epic_rei_lmao:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[client-1.18.1-20211210.034407-srg.jar%2397!/:?] {re:classloading,pl:accesstransformer:B,pl:epic_rei_lmao:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.18.1-20211210.034407-srg.jar%2397!/:?] {re:classloading,pl:accesstransformer:B,pl:epic_rei_lmao:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 8126235280 bytes (7749 MiB) / 10737418240 bytes (10240 MiB) up to 10737418240 bytes (10240 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): 2.59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 2070
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f14
	Graphics card #0 versionInfo: DriverVersion=27.21.14.6231
	Graphics card #1 name: Intel(R) UHD Graphics
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x9bc4
	Graphics card #1 versionInfo: DriverVersion=26.20.100.7642
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 42829.01
	Virtual memory used (MB): 28505.43
	Swap memory total (MB): 26624.00
	Swap memory used (MB): 1617.25
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmn128M -Xmx10240M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Server Running: true
	Player Count: 0 / 8; []
	Data Packs: vanilla, mod:configured (incompatible), mod:bno, mod:supermartijn642configlib, mod:simpleplanes (incompatible), mod:solarhelmet (incompatible), mod:betterfurnacesreforged (incompatible), mod:treeharvester, mod:wirelesschargers, mod:supermartijn642corelib, mod:tesseract, mod:scannable (incompatible), mod:forge, mod:easy_villagers, mod:curios, mod:collective, mod:ring_of_repair, mod:zerocore (incompatible), mod:bigreactors (incompatible), mod:justabattery (incompatible), mod:journeymap, file/anti enderman grief v1.1.2.zip, file/anti ghast grief v1.1.2.zip, file/armored elytra v1.0.5.zip, file/dragon drops v1.3.2.zip, file/redstone rotation wrench v1.1.3.zip, file/anti creeper grief v1.1.2.zip, mod:spawnermod (incompatible), mod:enchdesc, mod:ringsofascension (incompatible), mod:patchouli, mod:roughlyenoughitems (incompatible), mod:architectury (incompatible), mod:rei_internals_workaround (incompatible), mod:cloth_config (incompatible), mod:packedup, mod:oreexcavation, mod:solarenergy (incompatible), mod:oretweaker, mod:caelus, mod:refinedpipes, mod:mob_grinding_utils, mod:tlskincape (incompatible), mod:refinedstorage, mod:lightoverlay (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	OptiFine Version: OptiFine_1.18.1_HD_U_H5_pre5
	OptiFine Build: 20220208-201221
	Render Distance Chunks: 23
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: (internal)
	OpenGlVersion: 3.2.0 NVIDIA 462.31
	OpenGlRenderer: GeForce RTX 2070/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12
	ModLauncher: 9.1.0+9.1.0+main.6690ee51
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 OptiFine TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		client-1.18.1-20211210.034407-srg.jar             |Minecraft                     |minecraft                     |1.18.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		EnchantmentDescriptions-Forge-1.18.1-9.0.11.jar   |EnchantmentDescriptions       |enchdesc                      |9.0.11              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		supermartijn642configlib-1.0.9-mc1.18.jar         |SuperMartijn642's Config Lib  |supermartijn642configlib      |1.0.9               |DONE      |Manifest: NOSIGNATURE
		treeharvester_1.18.1-4.2.jar                      |Tree Harvester                |treeharvester                 |4.2                 |DONE      |Manifest: NOSIGNATURE
		refinedpipes-0.6.1.jar                            |Refined Pipes                 |refinedpipes                  |0.6.1               |DONE      |Manifest: NOSIGNATURE
		wirelesschargers-1.0.5-mc1.18.jar                 |wirelesschargers              |wirelesschargers              |1.0.5               |DONE      |Manifest: NOSIGNATURE
		supermartijn642corelib-1.0.16b-mc1.18.jar         |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.0.16b             |DONE      |Manifest: NOSIGNATURE
		packedup-1.0.25-mc1.18.jar                        |PackedUp                      |packedup                      |1.0.25              |DONE      |Manifest: NOSIGNATURE
		tesseract-1.0.25-mc1.18.jar                       |Tesseract                     |tesseract                     |1.0.25              |DONE      |Manifest: NOSIGNATURE
		scannable-1.18.1-forge-1.7.6+da03abb.jar          |Scannable                     |scannable                     |1.7.6               |DONE      |Manifest: NOSIGNATURE
		RoughlyEnoughItems-7.1.380.jar                    |Roughly Enough Items (REI)    |roughlyenoughitems            |7.1.380             |DONE      |Manifest: NOSIGNATURE
		caelus-forge-1.18-3.0.0.1.jar                     |Caelus API                    |caelus                        |1.18-3.0.0.1        |DONE      |Manifest: NOSIGNATURE
		easy_villagers-1.18.1-1.0.2.jar                   |Easy Villagers                |easy_villagers                |1.18.1-1.0.2        |DONE      |Manifest: NOSIGNATURE
		RingsOfAscension-1.18-1.0.0.jar                   |Rings of Ascension            |ringsofascension              |1.0.0               |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.18.1-5.0.6.2.jar                   |Curios API                    |curios                        |1.18.1-5.0.6.2      |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.18.1-65.jar                           |Patchouli                     |patchouli                     |1.18.1-65           |DONE      |Manifest: NOSIGNATURE
		collective-1.18.1-4.7.jar                         |Collective                    |collective                    |4.7                 |DONE      |Manifest: NOSIGNATURE
		RingOfRepair-Forge-1.18.1-1.4.4.jar               |Ring of Repair                |ring_of_repair                |1.4.4               |DONE      |Manifest: NOSIGNATURE
		journeymap-1.18.1-5.8.0beta17.jar                 |Journeymap                    |journeymap                    |5.8.0beta17         |DONE      |Manifest: NOSIGNATURE
		OreExcavation-1.10.160.jar                        |OreExcavation                 |oreexcavation                 |1.10.160            |DONE      |Manifest: NOSIGNATURE
		JustABattery-39.2.0.jar                           |JustABattery                  |justabattery                  |39.2.0              |DONE      |Manifest: NOSIGNATURE
		configured-1.5.3-1.18.1.jar                       |Configured                    |configured                    |1.5.3               |DONE      |Manifest: NOSIGNATURE
		BasicNetherOres-1.18.1-7.1.2.jar                  |Basic Nether Ores             |bno                           |7.1.2               |DONE      |Manifest: NOSIGNATURE
		forge-branders-spawnermod-1.18-1.8.14.jar         |Enhanced Mob Spawners         |spawnermod                    |1.8.14              |DONE      |Manifest: NOSIGNATURE
		simpleplanes-1.18.1-4.11.1.jar                    |Simple Planes                 |simpleplanes                  |1.18.1-4.11.1       |DONE      |Manifest: NOSIGNATURE
		SolarHelmet-1.18-38.0.0.jar                       |SolarHelmet                   |solarhelmet                   |38.0.0              |DONE      |Manifest: NOSIGNATURE
		solarenergy-1.18.1-0.4.0.3.jar                    |Solar Energy                  |solarenergy                   |0.4.0.3             |DONE      |Manifest: NOSIGNATURE
		BetterFurnacesReforged-1.18.1-1.2.4.jar           |BetterFurnaces Reforged       |betterfurnacesreforged        |1.18.1-1.2.4        |DONE      |Manifest: NOSIGNATURE
		architectury-3.7.31.jar                           |Architectury                  |architectury                  |3.7.31              |DONE      |Manifest: NOSIGNATURE
		RoughlyEnoughItems-jei-internals-workaround-7.3.44|REI Internals Workaround      |rei_internals_workaround      |7.3.443             |DONE      |Manifest: NOSIGNATURE
		light-overlay-6.0.4-forge.jar                     |Light Overlay                 |lightoverlay                  |6.0.4               |DONE      |Manifest: NOSIGNATURE
		cloth-config-6.1.50-forge.jar                     |Cloth Config v4 API           |cloth_config                  |6.1.50              |DONE      |Manifest: NOSIGNATURE
		forge-1.18.1-39.0.88-universal.jar                |Forge                         |forge                         |39.0.88             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		tl_skin_cape_forge_1.18_1.18.1-1.24.jar           |TLSkinCape                    |tlskincape                    |1.24                |DONE      |Manifest: 19:f5:ce:44:81:0c:e4:22:05:5e:73:c5:a8:cd:de:f3:c8:cf:a9:b3:01:70:40:a0:ee:2d:50:7a:1c:3d:1c:8a
		mob_grinding_utils-1.18.1-0.4.33.jar              |Mob Grinding Utils            |mob_grinding_utils            |1.18.1-0.4.33       |DONE      |Manifest: NOSIGNATURE
		refinedstorage-1.10.0.jar                         |Refined Storage               |refinedstorage                |1.10.0              |DONE      |Manifest: NOSIGNATURE
		ZeroCore2-1.18.1-2.1.11.jar                       |Zero CORE 2                   |zerocore                      |1.18.1-2.1.11       |DONE      |Manifest: NOSIGNATURE
		ExtremeReactors2-1.18.1-2.0.38.jar                |Extreme Reactors              |bigreactors                   |1.18.1-2.0.38       |DONE      |Manifest: NOSIGNATURE
		OreTweaker-1.18.1-3.0.2.jar                       |Ore Tweaker                   |oretweaker                    |3.0.2               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 7951eff8-0759-4a46-801e-e20a45e8f792
	FML: 39.0
	Forge: net.minecraftforge:39.0.88

**Comment by Wilyicaro** [comment]
Apparently you are using the Xp Tank Upgrade, I could say that it is an incompatibility with some mod, but I would need to know every detail for this crash to occur in your Extreme Forge (like the items you had in the forge) and try to reproduce this in my tests.

**Comment by Wilyicaro** [comment]
Thank you very much for reporting the bug, I already fixed it apparently in the last version of the mod that I didn't release on CurseForge.

**Comment by Wilyicaro** [comment]
#60
