### ISSUE TITLE
Crash whit equipment 

### ISSUE THREAD

**Issue by Heretic-117** [Wilyicaro/BetterFurnacesReforged#74]
I've put some equipment in my chest that feed the Forge to smelt them and it instantly crashed.

BFR 0.2.0 Fabric
Minecraft 1.19.3

Crash Report:

```
 ---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2023-02-07 21:10:06
Description: Ticking block entity

java.lang.IllegalArgumentException: Amount may not be negative, but it is: -16
	at net.fabricmc.fabric.api.transfer.v1.storage.StoragePreconditions.notNegative(StoragePreconditions.java:50)
	at net.fabricmc.fabric.api.transfer.v1.storage.base.CombinedStorage.extract(CombinedStorage.java:86)
	at wily.betterfurnaces.fabric.BetterFurnacesPlatformImpl.smeltingAutoIO(BetterFurnacesPlatformImpl.java:63)
	at wily.betterfurnaces.BetterFurnacesPlatform.smeltingAutoIO(BetterFurnacesPlatform.java)
	at wily.betterfurnaces.blockentity.AbstractSmeltingBlockEntity.tick(AbstractSmeltingBlockEntity.java:534)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:659)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:713)
	at net.minecraft.class_1937.method_18471(class_1937.java:472)
	at net.minecraft.class_3218.method_18765(class_3218.java:379)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:830)
	at net.minecraft.class_1132.method_3748(class_1132.java:99)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.fabricmc.fabric.api.transfer.v1.storage.StoragePreconditions.notNegative(StoragePreconditions.java:50)
	at net.fabricmc.fabric.api.transfer.v1.storage.base.CombinedStorage.extract(CombinedStorage.java:86)
	at wily.betterfurnaces.fabric.BetterFurnacesPlatformImpl.smeltingAutoIO(BetterFurnacesPlatformImpl.java:63)
	at wily.betterfurnaces.BetterFurnacesPlatform.smeltingAutoIO(BetterFurnacesPlatform.java)
	at wily.betterfurnaces.blockentity.AbstractSmeltingBlockEntity.tick(AbstractSmeltingBlockEntity.java:534)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:659)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:713)
	at net.minecraft.class_1937.method_18471(class_1937.java:472)
	at net.minecraft.class_3218.method_18765(class_3218.java:379)

-- Block entity being ticked --
Details:
	Name: betterfurnacesreforged:diamond_forge // wily.ultimatefurnaces.blockentity.DiamondForgeBlockEntity
	Block: Block{betterfurnacesreforged:diamond_forge}[colored=false,facing=up,lit=true,show_orientation=false,waterlogged=false]
	Block location: World: (-567,56,838), Section: (at 9,8,6 in -36,3,52; chunk contains blocks -576,-64,832 to -561,319,847), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,-64,512 to -513,319,1023)
	Block: Block{betterfurnacesreforged:diamond_forge}[colored=false,facing=up,lit=true,show_orientation=false,waterlogged=false]
	Block location: World: (-567,56,838), Section: (at 9,8,6 in -36,3,52; chunk contains blocks -576,-64,832 to -561,319,847), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,-64,512 to -513,319,1023)
Stacktrace:
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:659)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:713)
	at net.minecraft.class_1937.method_18471(class_1937.java:472)
	at net.minecraft.class_3218.method_18765(class_3218.java:379)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:830)
	at net.minecraft.class_1132.method_3748(class_1132.java:99)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 1 total; [class_3222['Heretic_117'/177, l='ServerLevel[FCN]', x=-566.61, y=56.00, z=841.60]]
	Chunk stats: 4810
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,134,0), Section: (at 0,6,0 in 0,8,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 2263065 game time, 2369622 day time
	Level name: FCN
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 23753 (now: false), thunder time: 53439 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:830)
	at net.minecraft.class_1132.method_3748(class_1132.java:99)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.19.3
	Minecraft Version ID: 1.19.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 3516563072 bytes (3353 MiB) / 8556380160 bytes (8160 MiB) up to 25769803776 bytes (24576 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 3700X 8-Core Processor             
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: AMD Radeon RX 5700 XT
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x731f
	Graphics card #0 versionInfo: DriverVersion=31.0.12029.10015
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 37297.70
	Virtual memory used (MB): 24684.84
	Swap memory total (MB): 4608.00
	Swap memory used (MB): 132.75
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx24G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advancednetherite: Advanced Netherite 1.6.6-1.19.3
		advancementplaques: Advancement Plaques 1.4.8
		animal_feeding_trough: Animal Feeding Trough 1.0.3+1.19.3
		architectury: Architectury 7.1.70
		attributefix: AttributeFix 18.0.1
		badpackets: Bad Packets 0.3.4
		bclib: BCLib 2.2.4
		bedbenefits: BedBenefits 10.0.1
		betterend: Better End 3.1.2
		betterfurnacesreforged: BetterFurnaces Reforged 1.19.3-0.2.0
		betternether: Better Nether 8.1.3
		bookshelf: Bookshelf 17.0.3
		borderlessmining: Borderless Mining 1.1.6+1.19.3
		capybara: Capybara 2.0.1
		clickthrough: ClickThrough 1.19.3-fabric0.68.1-0.4
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
			gbfabrictools: GBfabrictools 1.3.4+1.19.3
		cloth-config: Cloth Config v9 9.0.94
			cloth-basic-math: cloth-basic-math 0.6.1
		compact_storage: Compact Storage 5.0.2_1.19.3
		compressedblocks: Compressed Blocks 1.8
		continuity: Continuity 3.0.0-alpha.2+1.19.3
		dankstorage: Dank Storage 1.19.3-4.4
		diggusmaximus: Diggus Maximus 1.5.8-1.19.3
			kyrptconfig: Kyrpt Config 1.5.1-1.19.3
		dragonloot: DragonLoot 1.1.3
		dungeon_difficulty: Dungeon Difficulty 2.0.0+1.19.3
			com_github_zsoltmolnarrr_tinyconfig: TinyConfig 2.1.1
		dynmap: Dynmap 3.5-beta-2
		enchdesc: EnchantmentDescriptions 14.0.4
		entityculling: EntityCulling-Fabric 1.5.2-mc1.19.3
			com_logisticscraft_occlusionculling: occlusionculling 0.0.6-SNAPSHOT
		fabric-api: Fabric API 0.73.0+1.19.3
			fabric-api-base: Fabric API Base 0.4.20+afca2f3e85
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.19+49abcf7e85
			fabric-biome-api-v1: Fabric Biome API (v1) 12.1.0+b5d379b085
			fabric-block-api-v1: Fabric Block API (v1) 1.0.4+e022e5d185
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.29+c6af733c85
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.11+1134c5b885
			fabric-command-api-v1: Fabric Command API (v1) 1.2.21+f71b366f85
			fabric-command-api-v2: Fabric Command API (v2) 2.2.0+3fc4752e85
			fabric-commands-v0: Fabric Commands (v0) 0.2.38+df3654b385
			fabric-containers-v0: Fabric Containers (v0) 0.1.46+df3654b385
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.0+1d37d50285
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.1+8e4e694f85
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.13+aeb40ebe85
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.2.0+06937c4b85
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.40+48349a3f85
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.6+b83334a085
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.39+3baeb27a85
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.43+df3654b385
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.29+99f9db8085
			fabric-item-api-v1: Fabric Item API (v1) 2.1.9+c3530bb185
			fabric-item-group-api-v1: Fabric Item Group API (v1) 2.1.11+1134c5b885
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.30+bc01e09785
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.28+df3654b385
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.9+23a79c8a85
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.19+75e9821185
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.23+9e7660c685
			fabric-message-api-v1: Fabric Message API (v1) 5.0.13+6ede1da985
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.30+49abcf7e85
			fabric-models-v0: Fabric Models (v0) 0.3.26+11ba9c3b85
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.16+4017a8cb85
			fabric-networking-v0: Fabric Networking (v0) 0.3.33+df3654b385
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 5.4.0+eb2a3ba985
			fabric-particles-v1: Fabric Particles (v1) 1.0.19+f1e4495b85
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.0+5176f73d85
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.0.4+1134c5b885
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.2.0+9f179aa185
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.7.0+9f179aa185
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.29+df3654b385
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.24+afca2f3e85
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.17+f1e4495b85
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.32+df3654b385
			fabric-rendering-v1: Fabric Rendering (v1) 1.12.0+eb2a3ba985
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.2.2+1134c5b885
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.10.4+a91e48b785
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.40+f1e4495b85
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.12+99f9db8085
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.7+75e9821185
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.14+ccd377ba85
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 2.3.0+5b9a588b85
		fabricenchantments: Fabric Enchantments 0.9.1
		fabricloader: Fabric Loader 0.14.13
		factory_api: Factory API 1.19.3-0.1.6
			team_reborn_energy: Energy 2.3.0
		ferritecore: FerriteCore 5.1.0
		forgeconfigapiport: Forge Config API Port 5.0.7
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		graveyard_biomes: The Graveyard Biomes 1.8
			omega-config: OmegaConfig 1.2.2-1.18.1
		harvest_scythes: Harvest Scythes 2.5.5+mc1.19.3
			mm: Manningham Mills 2.3
		iceberg: Iceberg 1.1.4
		indium: Indium 1.0.12+mc1.19.3
		inventorysorter: Inventory Sorter 1.8.10-1.19.3
		iris: Iris 1.5.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre8
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 12.1.1.13
		krypton: Krypton 0.2.1
			com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT
		lazydfu: LazyDFU 0.1.3
		maxhealthfix: MaxHealthFix 9.0.1
		mcwbridges: Macaw's Bridges 2.0.6
		memoryleakfix: memory Leak Fix 1.19.3-0.7.0
		minecraft: Minecraft 1.19.3
		modmenu: Mod Menu 5.0.2
		neat: Neat 1.19.3-33-FABRIC
			fiber: fiber 0.23.0-2
		openpartiesandclaims: Open Parties and Claims 0.16.6
		origins: Origins 1.8.1
			apoli: Apoli 2.7.1
				additionalentityattributes: Additionalentityattributes 1.2.0+1.19.3
				calio: Calio 1.8.0
				playerabilitylib: Pal 1.7.0
			reach-entity-attributes: Reach Entity Attributes 2.3.1
		origins-plus-plus: Origins++ 2.0
		pehkui: Pehkui 3.6.3+1.14.4-1.19.3
			kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		phosphor: Phosphor 0.8.1
		pickablevillagers: Pickable Villagers 1.3.6+1.19.3
		projectile_damage: Projectile Damage Attribute 3.0.0+1.19.3
		reeses-sodium-options: Reese's Sodium Options 1.4.9+mc1.19.2-build.67
		reinfchest: Reinforced Chests 2.3.0+1.19
			reinfcore: Reinforced Core 3.0.4+1.19
		ring_of_attraction: Ring Of Attraction 1.4.6
		sodium: Sodium 0.4.8+build.22
		sodium-extra: Sodium Extra 0.4.16+mc1.19.3-build.91
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		structory: Structory 1.0.1
		t_and_t: Towns and Towers 1.10.1
			blue_endless_jankson: jankson 1.2.1
		terrablender: TerraBlender 2.1.0.134
		terralith: Terralith 2.3
		toolstats: ToolStats 13.0.1
		trade_cycling: Trade Cycling 1.19.3-1.0.5
		travelersbackpack: Traveler's Backpack 1.19.3-8.3.1
		trinkets: Trinkets 3.5.1
			cardinal-components-base: Cardinal Components API (base) 5.1.0
			cardinal-components-entity: Cardinal Components API (entities) 5.1.0
		wthit: wthit 6.1.4
		xaerominimap: Xaero's Minimap 22.17.1
		xaeroworldmap: Xaero's World Map 1.28.8
		yigd: You're in Grave Danger 1.5.1
	Loaded Shaderpack: ComplementaryShaders_v4.7.1.zip
		Profile: Custom (+19 options changed by user)
	NEC status: No NEC detected
	Server Running: true
	Player Count: 1 / 8; [class_3222['Heretic_117'/177, l='ServerLevel[FCN]', x=-566.61, y=56.00, z=841.60]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: fabric-loader-0.14.13-1.19.3
```

**Comment by Wilyicaro** [comment]
Did it start to occur from 0.2.0, or did you not test it before?

**Comment by Heretic-117** [comment]
Didn't play with the mod on previous version.

**Comment by Wilyicaro** [comment]
Thanks for warning about this crash, I will investigate this further and will release a fix soon

**Comment by Wilyicaro** [comment]
Could you better describe how it happened, like the items in the chest, the upgrades used...

**Comment by Heretic-117** [comment]
I was using the Diamond forge with the Factory upgrade, and i've put a gold helmet and a crossbow on my chest.

**Comment by Heretic-117** [comment]
And the forge was smelting some ancient debris in the same time (probably not related to the crash)

**Comment by Wilyicaro** [comment]
Thanks for detailing, I found what went wrong, soon I will release the 1.19.3-2.1 version

**Comment by Heretic-117** [comment]
That was quick haha, thanks for that ! :)

**Comment by Wilyicaro** [comment]
You're welcome!
