### ISSUE TITLE
[Bug] Generator Upgrade makes any 1.19.4 Servers crash

### ISSUE THREAD

**Issue by Jovalii** [Wilyicaro/BetterFurnacesReforged#91]
**Mod Version-Minecraft Version**
Fabric server 1.19.4

Mod Loader Version
fabric-api-0.81.1+1.19.4
betterfurnaces-fabric-1.19.4-0.1.0

**Bug/Glitch Occurrence Context**
When placing the Generator Upgrade in any furnace, the server crash. 

*Crash Report
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/class_1074
	at wily.betterfurnaces.blockentity.SmeltingBlockEntity.IgetName(SmeltingBlockEntity.java:328)
	at wily.betterfurnaces.blockentity.InventoryBlockEntity.method_5477(InventoryBlockEntity.java:85)
	at wily.betterfurnaces.blockentity.InventoryBlockEntity.method_5476(InventoryBlockEntity.java:139)
	at wily.betterfurnaces.blockentity.SmeltingBlockEntity.method_5476(SmeltingBlockEntity.java:996)
	at dev.architectury.registry.menu.fabric.MenuRegistryImpl$1.method_5476(MenuRegistryImpl.java:53)
	at net.minecraft.class_3222.method_17355(class_3222.java:1039)
	at dev.architectury.registry.menu.fabric.MenuRegistryImpl.openExtendedMenu(MenuRegistryImpl.java:45)
	at dev.architectury.registry.menu.MenuRegistry.openExtendedMenu(MenuRegistry.java)
	at wily.betterfurnaces.blocks.SmeltingBlock.interactWith(SmeltingBlock.java:167)
	at wily.betterfurnaces.blocks.SmeltingBlock.method_9534(SmeltingBlock.java:121)
	at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:1009)
	at net.minecraft.class_3225.redirect$zib000$carpet$activateWithOptionalCactus(class_3225.java:1529)
	at net.minecraft.class_3225.method_14262(class_3225.java:342)
	at net.minecraft.class_3244.method_12046(class_3244.java:1140)
	at net.minecraft.class_2885.method_12547(class_2885.java:34)
	at net.minecraft.class_2885.method_11054(class_2885.java:8)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:786)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:165)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:768)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:762)
	at net.minecraft.class_1255.method_18857(class_1255.java:139)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:747)
	at net.minecraft.server.MinecraftServer.handler$zfd000$carpet$modifiedRunLoop(MinecraftServer.java:7945)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:654)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:266)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_1074
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 31 more

**Comment by Wilyicaro** [comment]
Sorry for the delay in support, but the bug has been fixed as of versions 1.19.4-1.1 and 1.20.1-1.0
